### ISSUE TITLE
I really like Layercake but...

### ISSUE THREAD

**Issue by algonorth** [mhkeller/layercake-template#25]
I really like Layercake but where are the basic pie and donut charts?! ;)

**Comment by mhkeller** [comment]
I talked this comment over with a colleague who thought that you were making a joke about baked goods you want to eat related to the cakey-ness of this library. 

I thought you were genuinely looking for examples of pie and donut charts. If that's the case, sadly I have not made any. I haven't found a use case for them and generally find bar/column charts to be more preferable except in limited scenarios where you're constrained somehow by the layout — such as if you're making a dashboard.

The good news: I made layercake with the design goal that I am not a bottleneck for anyone who wants to make whatever kind of chart they want to and you don't have to depend on — or listen to — my opinions about chart forms.

So, by all means, make those charts! Take a look at [d3-shape](https://d3js.org/d3-shape/pie) which will compute the necessary angles for. And here's a [non-svelte implementation](https://observablehq.com/@d3/pie-settings) that can give you an idea about how to construct the SVGs. 

If you want to paste your final result here — or a REPL link with a basic version — for future pie and donut fans, please do.

**Comment by algonorth** [comment]
Pun was intended but yes I would like donut charts and I was hoping to use a Svelte implementation. I'm currently working on some backend stuff at the moment but as soon as I have a moment to make donut charts I'll definitely post the code here.

**Comment by mhkeller** [comment]
Closing this for now but feel free to report back on your progress.
